### ISSUE TITLE
Added support for proxy-url from config

### ISSUE THREAD

**Issue by kxalex** [boz/kail#65]
Hello,

Since 1.19 kube supports proxy-url per cluster.

This was added here https://github.com/kubernetes/kubernetes/pull/81443

Sample config:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REMOVED
    server: https://api.some-server.com
    proxy-url: http://some-proxy:1234
  name: cluster-name
contexts:
- context:
    cluster: cluster-name
    namespace: default
    user: user
  name: default
kind: Config
preferences: {}
users:
- name: cluster-name
  user:
    password: REMOVED
    username: admin
- name: cluster-name-basic-auth
  user:
    password: REMOVED
    username: admin
```

Could you please honour this proxy-url property from config?

If you have few clusters with different proxies it's not that convenient to set http_proxy before using Kail.
